// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementAPI.Data;

#nullable disable

namespace RestaurantManagementAPI.Migrations
{
    [DbContext(typeof(QLNHDbContext))]
    partial class QLNHDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaNV");

                    b.Property<string>("ChucVu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChucVu");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HoTen");

                    b.Property<DateTime?>("NgayVaoLam")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayVaoLam");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SDT");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaNV");

                    b.ToTable("NHANVIEN");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.Ban", b =>
                {
                    b.Property<string>("MaBan")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaBan");

                    b.Property<string>("TenBan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenBan");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaBan");

                    b.ToTable("BAN");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaMA")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaMA");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DonGia");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<decimal>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ThanhTien")
                        .HasComputedColumnSql("[SoLuong] * [DonGia]", true);

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaHD", "MaMA");

                    b.HasIndex("MaMA");

                    b.ToTable("CHITIETHOADON");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<string>("MaPN")
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaPN");

                    b.Property<string>("MaNL")
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaNL");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("MaPN", "MaNL");

                    b.HasIndex("MaNL");

                    b.ToTable("CHITIETPHIEUNHAP");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.DatBan", b =>
                {
                    b.Property<string>("MaDatBan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaDatBan");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaBan");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDienThoai");

                    b.Property<int>("SoNguoi")
                        .HasColumnType("int")
                        .HasColumnName("SoNguoi");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKhachHang");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianDat");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaDatBan");

                    b.HasIndex("MaBan");

                    b.ToTable("DATBAN");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.DonHangOnline", b =>
                {
                    b.Property<string>("MaDH")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaDH");

                    b.Property<DateTime?>("NgayTiepNhan")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTiepNhan");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKH")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenKH");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaDH");

                    b.ToTable("DONHANG_ONLINE");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaBan")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaBan");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaNV");

                    b.Property<DateTime?>("NgayLap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayLap");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PaymentMethod");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TongTien");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaHD");

                    b.HasIndex("MaBan");

                    b.HasIndex("MaNV");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.Kho", b =>
                {
                    b.Property<string>("MaNL")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaNL");

                    b.Property<string>("DonVi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DonVi");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongTon");

                    b.Property<string>("TenNL")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenNL");

                    b.HasKey("MaNL");

                    b.ToTable("KHO");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.MonAn", b =>
                {
                    b.Property<string>("MaMA")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaMA");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DonGia");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HinhAnh");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Loai");

                    b.Property<string>("TenMA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TenMA");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaMA");

                    b.ToTable("MONAN");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.PhieuNhapKho", b =>
                {
                    b.Property<string>("MaPN")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaPN");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("MaNV")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaNV");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayNhap");

                    b.HasKey("MaPN");

                    b.HasIndex("MaNV");

                    b.ToTable("PHIEUNHAPKHO");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TenDangNhap");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("HoatDong");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit")
                        .HasColumnName("IsVerified");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("OTP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OTP");

                    b.Property<DateTime?>("OTPExpireTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("OTPExpireTime");

                    b.Property<bool>("Online")
                        .HasColumnType("bit")
                        .HasColumnName("Online");

                    b.Property<string>("Quyen")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Quyen");

                    b.HasKey("TenDangNhap");

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.ToTable("TAIKHOAN");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.ChiTietHoaDon", b =>
                {
                    b.HasOne("RestaurantManagementAPI.Models.Entities.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagementAPI.Models.Entities.MonAn", "MonAn")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaMA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("MonAn");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("RestaurantManagementAPI.Models.Entities.Kho", "Kho")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaNL")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestaurantManagementAPI.Models.Entities.PhieuNhapKho", "PhieuNhapKho")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");

                    b.Navigation("PhieuNhapKho");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.DatBan", b =>
                {
                    b.HasOne("RestaurantManagementAPI.Models.Entities.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ban");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.HoaDon", b =>
                {
                    b.HasOne("RestaurantManagementAPI.Models.Entities.Ban", "Ban")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaBan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.PhieuNhapKho", b =>
                {
                    b.HasOne("NhanVien", "NhanVien")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.TaiKhoan", b =>
                {
                    b.HasOne("NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("RestaurantManagementAPI.Models.Entities.TaiKhoan", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("NhanVien", b =>
                {
                    b.Navigation("HoaDons");

                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.Ban", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.Kho", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.MonAn", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("RestaurantManagementAPI.Models.Entities.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });
#pragma warning restore 612, 618
        }
    }
}
